### ISSUE TITLE
nice to have

### ISSUE THREAD

**Issue by mosesokemwa** [mussaimo/linux-install#2]
Installation for 32-bit and 64-bit architecture
- checks if the system is either of the two
- initiates install for detected arch type

**Comment by newtonkiragu** [comment]
Hey, I found a command that checks for the system architecture. However, as i was reading through, I noticed that as long as you are installing things via terminal, the system downloads the software based on the architecture automatically
```
getconf LONG_BIT
```

**Comment by mosesokemwa** [comment]
sweet, then I can close this issue
